apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins
  namespace: ufawkespipe
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"  # Uncomment for TLS
spec:
  ingressClassName: nginx
  # tls:  # Uncomment for TLS
  # - hosts:
  #   - jenkins.yourdomain.com
  #   secretName: jenkins-tls
  rules:
    - host: jenkins.yourdomain.com # Change to your domain
      http:
        paths:
          - path: /jenkins
            pathType: Prefix
            backend:
              service:
                name: jenkins
                port:
                  number: 8080
